Repository FRONT-END-BOOTCAMP-PLUS-4/YAK_AL_GO, pull requests merged in 2025-06, with the labels that each got.

#103 마우스 따라다니는 캐릭터 추가
  app/layout.tsx
  components/MouseFollower.tsx
Labels: feat

#107 회원가입(약사)페이지 refactor 일반 사용자 기능 동기화 구현
  app/(anon-user)/auth/signup-step/page.tsx
  components/auth/GeneralForm.tsx
  components/auth/PharmacistForm.tsx
  components/auth/ProgressIndicator.tsx
Labels: refactor

#125 게시물/질문 수정 시 제목 필드 초기값 설정 오류 해결
  app/member/posts/[id]/edit/page.tsx
  app/member/qnas/[id]/edit/page.tsx
Labels: fix

#129 [fix/#128]fix: title.current 문 삭제
  app/member/qnas/[id]/edit/page.tsx
Labels: fix

#132 [feat] Create README.md
  README.md
Labels: feat

#133 [chore]Update README.md
  README.md
Labels: chore

#134 [fix/#128] fix: title의 useRef 활용하던 구문 삭제
  app/member/qnas/[id]/edit/page.tsx
Labels: fix

#137 [chore] google ads 에 필요한 태그 설정
  app/layout.tsx
Labels: chore
