Repository FRONT-END-BOOTCAMP-PLUS-4/YAK_AL_GO, pull requests merged in 2025-05, with the labels that each got.

#9 [feat/#8] : schema 파일 모델링
  prisma/generated/edge.js
  prisma/generated/index-browser.js
  prisma/generated/index.d.ts
  prisma/generated/index.js
  prisma/generated/package.json
  prisma/generated/schema.prisma
  prisma/generated/wasm.js
  prisma/migrations/20250514082731_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/test.ts
Labels: feat

#12 prisma client generated 후 pirsma.ts설정
  app/(anon-user)/auth/signup/layout.tsx
  lib/prisma.ts
  package-lock.json
  package.json
  prisma/generated/edge.js
  prisma/generated/index.js
  tsconfig.json
Labels: feat

#15 Fix/14 fix new prisma client/park
  .gitignore
  lib/prisma.ts
  package.json
Labels: fix

#20 [feat/#19] 원격 브랜치 개명 적용
  .gitignore
  app/(anon-user)/auth/signup/layout.tsx
  app/(anon-user)/community/page.tsx
  app/(anon-user)/posts/page.tsx
  app/(anon-user)/qnas/page.tsx
  app/api/posts/route.ts
  app/layout.tsx
  app/member-user/posts/new/page.tsx
  application/application.ts
  application/usecases/CreatePostUsecase.ts
  application/usecases/dto/CreatePostRequestDto.ts
  domain/entities/Answer.ts
  domain/entities/Comment.ts
  domain/entities/Post.ts
  domain/entities/Qna.ts
  domain/entities/Tag.ts
  domain/entities/User.ts
  domain/repositories/AnswerRepository.ts
  domain/repositories/CommentRepository.ts
  domain/repositories/PostRepository.ts
  domain/repositories/QnaRepository.ts
  domain/repositories/TagRepository.ts
  infra/repositories/prisma/PrismaPostRepository.ts
  infra/repositories/prisma/PrismaTagRepository.ts
  infra/repositories/supabase/test.ts
  lib/prisma.ts
  package-lock.json
  package.json
  prisma/generated/edge.js
  prisma/generated/index-browser.js
  prisma/generated/index.d.ts
  prisma/generated/index.js
  prisma/generated/package.json
  prisma/generated/schema.prisma
  prisma/generated/wasm.js
  prisma/migrations/20250514082731_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/test.ts
  src/components/ui/color-mode.tsx
  src/components/ui/provider.tsx
  src/components/ui/toaster.tsx
  src/components/ui/tooltip.tsx
  tsconfig.json
Labels: chore

#25 [fix/#24] tsconfig파일 내용 수정
  app/favicon.ico
  app/globals.scss
  app/styles/definition.scss
  components/rootFooter/RootFooter.tsx
  components/rootFooter/rootFooter.scss
  components/rootHeader/RootHeader.tsx
  components/rootHeader/rootHeader.scss
  tsconfig.json
Labels: fix

#27 [refactor/#26] 모델링 복구
  package.json
  prisma/schema.prisma
Labels: refactor

#37 [chore/#35] header,footer 수정 및 아이콘 추가
  components/layout/footer.tsx
  components/layout/header.tsx
  components/ui/sheet.tsx
  public/icon.png
Labels: chore

#53 [feat/#52] feat: 게시물, 댓글관련 여러 기능 개발
  app/(anon-user)/community/page.tsx
  app/(anon-user)/community/posts/[id]/page.tsx
  app/(anon-user)/community/qnas/[id]/page.tsx
  app/api/comments/route.ts
  app/api/posts/[id]/route.ts
  app/api/posts/route.ts
  app/member/posts/write/editorInitialValue.ts
  app/member/posts/write/loading.tsx
  app/member/posts/write/page.tsx
  app/member/qnas/write/page.tsx
  backend/application/usecases/post/CreateCommentUsecase.ts
  backend/application/usecases/post/CreatePostUsecase.ts
  backend/application/usecases/post/GetAllPostsUsecase.ts
  backend/application/usecases/post/GetPostByIdUsecase.ts
  backend/application/usecases/post/dto/CommentDto.ts
  backend/application/usecases/post/dto/PostDto.ts
  backend/domain/entities/CommentEntity.ts
  backend/domain/entities/PostEntity.ts
  backend/domain/repositories/CommentRepository.ts
  backend/domain/repositories/PostRepository.ts
  backend/infra/repositories/prisma/PrismaCommentRepository.ts
  backend/infra/repositories/prisma/PrismaPostRepository.ts
  components/community/PostCard.tsx
  components/post/CommentForm.tsx
  components/post/CommentSection.tsx
  components/qna/AnswerSection.tsx
  lib/constants/queryKeys.ts
  lib/queries/getPost.ts
  lib/queries/usePosts.ts
Labels: feat

#69 재고 페이지 회원 정보 연결
  components/inventory/InventoryPage.tsx
Labels: feat

#80 Feat/73 memeber protected route/park
  app/(anon-user)/auth/page.tsx
  app/layout.tsx
  middleware.ts
Labels: feat
